### ISSUE TITLE
Parse error: syntax error, unexpected variable "$result"

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [TenGbps/pwnedpasswordscheck#1]
In ext/tengbps/pwnedpasswordscheck/event/listener.php

Change 
`$sql = 'SELECT user_id FROM ' . USERS_TABLE . ' WHERE username_clean = "' . $username_cleaned . '" LIMIT 1;'`

To
`$sql = 'SELECT user_id FROM ' . USERS_TABLE . ' WHERE username_clean = "' . $username_cleaned . '" LIMIT 1;';`

(Added missing semicolon)

______________

PHP: 8.3.14
phpBB: 3.3.14

**Comment by TenGbps** [comment]
Committed
